sudo: required
dist: trusty
language: cpp

compiler:
    - clang
    - gcc

os:
    - linux
    - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get update -qq && sudo apt-get install qt5-default; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update && brew install qt5; find $(brew --prefix)/opt/qt5 -type d; fi

script:
    - qmake
    - make
