sudo: required
dist: trusty
language: cpp

compiler:
    #- clang
    - gcc

os:
    #- linux
    - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get -y update -qq && sudo apt-get -y install qt5-default; fi
    - # if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install qt5; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then echo $(brew --prefix); fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then echo find $(brew --prefix)/qt5 -type d; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local -name qmake; fi

script:
    - qmake
    - make
